In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# 4.1
```



In [3]:
def length_conversion(value, conversion_type):
    """
    Convert length between meters and feet.

    Parameters:
    value (float): The value to be converted.
    conversion_type (str): The type of conversion ('m_to_ft' or 'ft_to_m').

    Returns:
    float: Converted value.
    """
    if conversion_type == "m_to_ft":
        return value * 3.28084  # 1 meter = 3.28084 feet
    elif conversion_type == "ft_to_m":
        return value / 3.28084  # 1 foot = 0.3048 meters
    else:
        return None

def weight_conversion(value, conversion_type):
    """
    Convert weight between kilograms and pounds.

    Parameters:
    value (float): The value to be converted.
    conversion_type (str): The type of conversion ('kg_to_lbs' or 'lbs_to_kg').

    Returns:
    float: Converted value.
    """
    if conversion_type == "kg_to_lbs":
        return value * 2.20462  # 1 kg = 2.20462 lbs
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462  # 1 lb = 0.453592 kg
    else:
        return None

def volume_conversion(value, conversion_type):
    """
    Convert volume between liters and gallons.

    Parameters:
    value (float): The value to be converted.
    conversion_type (str): The type of conversion ('L_to_gal' or 'gal_to_L').

    Returns:
    float: Converted value.
    """
    if conversion_type == "L_to_gal":
        return value * 0.264172  # 1 liter = 0.264172 gallons
    elif conversion_type == "gal_to_L":
        return value / 0.264172  # 1 gallon = 3.78541 liters
    else:
        return None

def main():
    """
    Main function to prompt user input and perform conversions.
    """
    print("Welcome to Unit Converter!")
    print("Select the conversion type:")
    print("1. Length (meters <-> feet)")
    print("2. Weight (kilograms <-> pounds)")
    print("3. Volume (liters <-> gallons)")

    try:
        choice = int(input("Enter your choice (1/2/3): "))
        if choice not in [1, 2, 3]:
            print("Invalid choice! Please select a valid option.")
            return

        value = float(input("Enter the value to convert: "))

        if choice == 1:
            print("1. Convert meters to feet")
            print("2. Convert feet to meters")
            length_choice = int(input("Enter your choice (1/2): "))
            conversion_type = "m_to_ft" if length_choice == 1 else "ft_to_m"
            result = length_conversion(value, conversion_type)

        elif choice == 2:
            print("1. Convert kilograms to pounds")
            print("2. Convert pounds to kilograms")
            weight_choice = int(input("Enter your choice (1/2): "))
            conversion_type = "kg_to_lbs" if weight_choice == 1 else "lbs_to_kg"
            result = weight_conversion(value, conversion_type)

        elif choice == 3:
            print("1. Convert liters to gallons")
            print("2. Convert gallons to liters")
            volume_choice = int(input("Enter your choice (1/2): "))
            conversion_type = "L_to_gal" if volume_choice == 1 else "gal_to_L"
            result = volume_conversion(value, conversion_type)

        print(f"Converted Value: {result:.4f}")

    except ValueError:
        print("Invalid input! Please enter a numeric value.")

# Run the program
if __name__ == "__main__":
    main()


Welcome to Unit Converter!
Select the conversion type:
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
Enter your choice (1/2/3): 2
Enter the value to convert: 400
1. Convert kilograms to pounds
2. Convert pounds to kilograms
Enter your choice (1/2): 2
Converted Value: 181.4372


# Task-2

In [5]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers using a for loop.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Sum of numbers.
    """
    total = 0
    for num in numbers:
        total += num
    return total

def calculate_average(numbers):
    """
    Calculate the average of a list of numbers using a for loop.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Average value.
    """
    total = 0
    count = 0
    for num in numbers:
        total += num
        count += 1
    return total / count if count > 0 else 0

def calculate_maximum(numbers):
    """
    Find the maximum number in a list using a for loop.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Maximum number.
    """
    max_value = numbers[0]
    for num in numbers:
        if num > max_value:
            max_value = num
    return max_value

def calculate_minimum(numbers):
    """
    Find the minimum number in a list using a for loop.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Minimum number.
    """
    min_value = numbers[0]
    for num in numbers:
        if num < min_value:
            min_value = num
    return min_value

def main():
    """
    Main function to prompt user input and perform calculations.
    """
    print("Math Operations on a List of Numbers")
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Enter your choice (1/2/3/4): "))
        if choice not in [1, 2, 3, 4]:
            print("Invalid choice! Please select a valid option.")
            return

        numbers = input("Enter numbers separated by spaces: ").split()
        numbers = [float(num) for num in numbers]

        if not numbers:
            print("Error: No numbers provided.")
            return

        if choice == 1:
            result = calculate_sum(numbers)
            operation = "Sum"
        elif choice == 2:
            result = calculate_average(numbers)
            operation = "Average"
        elif choice == 3:
            result = calculate_maximum(numbers)
            operation = "Maximum"
        else:
            result = calculate_minimum(numbers)
            operation = "Minimum"

        print(f"{operation} of given numbers: {result:.4f}")

    except ValueError:
        print("Invalid input! Please enter numeric values only.")


if __name__ == "__main__":
    main()


Math Operations on a List of Numbers
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1/2/3/4): 1
Enter numbers separated by spaces: 1 2 3 4 5 6 7 8 9 10
Sum of given numbers: 55.0000


# 4.3 Exercise on Nested List

In [7]:
def extract_every_other(lst):
    """
    Extracts every other element from the list, starting from the first element.
    """
    new_list = []
    i = 0
    while i < len(lst):
        new_list.append(lst[i])
        i += 2
    return new_list

def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list, from start to end (inclusive).
    """
    new_list = []
    i = start
    while i <= end:
        new_list.append(lst[i])
        i += 1
    return new_list

def reverse_list(lst):
    """
    Reverses the list without slicing.
    """
    new_list = []
    i = len(lst) - 1
    while i >= 0:
        new_list.append(lst[i])
        i -= 1
    return new_list

def remove_first_last(lst):
    """
    Removes the first and last elements of the list.
    """
    new_list = []
    i = 1
    while i < len(lst) - 1:
        new_list.append(lst[i])
        i += 1
    return new_list

def get_first_n(lst, n):
    """
    Extracts the first `n` elements from a list.
    """
    new_list = []
    i = 0
    while i < n and i < len(lst):
        new_list.append(lst[i])
        i += 1
    return new_list

def get_last_n(lst, n):
    """
    Extracts the last `n` elements from a list.
    """
    new_list = []
    i = len(lst) - n
    while i < len(lst):
        new_list.append(lst[i])
        i += 1
    return new_list

def reverse_skip(lst):
    """
    Extracts elements in reverse order, starting from the second-to-last element and skipping one element.
    """
    new_list = []
    i = len(lst) - 2
    while i >= 0:
        new_list.append(lst[i])
        i -= 2
    return new_list


def get_user_list():
    """
    Prompts the user to enter the number of elements and the list elements.
    """
    while True:
        try:
            n = int(input("Enter the number of elements in the list: "))
            if n <= 0:
                print("Please enter a positive integer.")
                continue
            break
        except ValueError:
            print("Invalid input! Please enter a valid integer.")

    user_list = []
    print(f"Enter {n} numbers one by one:")
    for i in range(n):
        while True:
            try:
                num = int(input(f"Enter element {i + 1}: "))
                user_list.append(num)
                break
            except ValueError:
                print("Invalid input! Please enter a number.")

    return user_list

if __name__ == "__main__":
    user_list = get_user_list()

    print("\nOperations on the list:")
    print("Every other element:", extract_every_other(user_list))

    while True:
        try:
            start = int(input("\nEnter start index for sublist: "))
            end = int(input("Enter end index for sublist: "))
            if 0 <= start <= end < len(user_list):
                break
            else:
                print("Invalid range! Start should be <= end and within list size.")
        except ValueError:
            print("Invalid input! Please enter numbers.")

    print("Sublist:", get_sublist(user_list, start, end))
    print("Reversed list:", reverse_list(user_list))
    print("Without first & last:", remove_first_last(user_list))

    while True:
        try:
            n = int(input("\nEnter number of elements to extract from the start: "))
            if n > 0:
                break
            else:
                print("Please enter a positive integer.")
        except ValueError:
            print("Invalid input! Please enter a valid integer.")

    print("First", n, "elements:", get_first_n(user_list, n))

    while True:
        try:
            n = int(input("\nEnter number of elements to extract from the end: "))
            if n > 0:
                break
            else:
                print("Please enter a positive integer.")
        except ValueError:
            print("Invalid input! Please enter a valid integer.")

    print("Last", n, "elements:", get_last_n(user_list, n))
    print("Reverse skipping:", reverse_skip(user_list))


Enter the number of elements in the list: 5
Enter 5 numbers one by one:
Enter element 1: 12
Enter element 2: 22
Enter element 3: 33
Enter element 4: 44
Enter element 5: 55

Operations on the list:
Every other element: [12, 33, 55]

Enter start index for sublist: 4
Enter end index for sublist: 6
Invalid range! Start should be <= end and within list size.

Enter start index for sublist: 0
Enter end index for sublist: 4
Sublist: [12, 22, 33, 44, 55]
Reversed list: [55, 44, 33, 22, 12]
Without first & last: [22, 33, 44]

Enter number of elements to extract from the start: 2
First 2 elements: [12, 22]

Enter number of elements to extract from the end: 2
Last 2 elements: [44, 55]
Reverse skipping: [44, 22]


# Numpy

`Problem - 1: Array Creation:`

In [8]:
import numpy as np

empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

ones_array = np.ones((4, 2))
print("\nAll-One Array (4x2):\n", ones_array)

fill_array = np.full((3, 3), 7)
print("\nArray filled with 7:\n", fill_array)

sample_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(sample_array)
print("\nArray of Zeros with same shape as sample array:\n", zeros_like_array)

ones_like_array = np.ones_like(sample_array)
print("\nArray of Ones with same shape as sample array:\n", ones_like_array)

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted List to NumPy Array:\n", numpy_array)


Empty Array (2x2):
 [[678.70025138 299.86666667]
 [700.70025138 313.86666667]]

All-One Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Array of Zeros with same shape as sample array:
 [[0 0 0]
 [0 0 0]]

Array of Ones with same shape as sample array:
 [[1 1 1]
 [1 1 1]]

Converted List to NumPy Array:
 [1 2 3 4]


`Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:`



In [9]:
arr_10_to_49 = np.arange(10, 50)
print("Array from 10 to 49:\n", arr_10_to_49)

matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix (0 to 8):\n", matrix_0_to_8)

identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

random_array = np.random.random(30)
mean_value = np.mean(random_array)
print("\nMean of Random Array:\n", mean_value)

random_matrix = np.random.random((10, 10))
min_value = np.min(random_matrix)
max_value = np.max(random_matrix)
print("\n10x10 Random Matrix Min & Max:\n", min_value, max_value)

zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th element replaced by 1:\n", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:\n", border_array)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of Random Array:
 0.5352799242412095

10x10 Random Matrix Min & Max:
 0.01457155294033774 0.9975298162236681

Zero Array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed Array:
 [0 4 0 0 2 1]

2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


`Problem 3: Array Operations`

In [10]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

addition_result = x + y
print("Addition of x and y:\n", addition_result)

subtraction_result = x - y
print("\nSubtraction of x and y:\n", subtraction_result)

multiplication_result = x * 2
print("\nMultiplication of x by 2:\n", multiplication_result)


square_result = x ** 2
print("\nSquare of each element in x:\n", square_result)

dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print("\nDot product of v and w:\n", dot_v_w)
print("\nDot product of x and v:\n", dot_x_v)
print("\nDot product of x and y:\n", dot_x_y)

concat_x_y = np.concatenate((x, y), axis=0)
print("\nConcatenation of x and y along rows:\n", concat_x_y)

concat_v_w = np.vstack((v, w))
print("\nConcatenation of v and w along columns:\n", concat_v_w)

try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v:\n", concat_x_v)
except ValueError as e:
    print("\nError when concatenating x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w:
 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


`Problem 4: Matrix Operations`

In [11]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A⁻¹ = I
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("A * A⁻¹ = Identity Matrix:\n", identity_check)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nMatrix AB:\n", AB)
print("\nMatrix BA:\n", BA)
if not np.array_equal(AB, BA):
    print("\nAB is NOT equal to BA")

# 3. Prove (AB)ᵀ = Bᵀ * Aᵀ
AB_transpose = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("\n(AB)ᵀ:\n", AB_transpose)
print("\nBᵀ * Aᵀ:\n", BT_AT)
if np.array_equal(AB_transpose, BT_AT):
    print("\n(AB)ᵀ is equal to Bᵀ * Aᵀ")

# 4. Solve Linear Equations using Inverse Methods
# System of equations:
#  2x - 3y + z = -1
#  x - y + 2z = -3
#  3x + y - z = 9

A_matrix = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3, 1, -1]])

B_matrix = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A_matrix)
solution = np.dot(A_inv, B_matrix)
print("\nSolution for Linear Equations (x, y, z):\n", solution)

A * A⁻¹ = Identity Matrix:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Matrix AB:
 [[23 13]
 [51 29]]

Matrix BA:
 [[36 44]
 [13 16]]

AB is NOT equal to BA

(AB)ᵀ:
 [[23 51]
 [13 29]]

Bᵀ * Aᵀ:
 [[23 51]
 [13 29]]

(AB)ᵀ is equal to Bᵀ * Aᵀ

Solution for Linear Equations (x, y, z):
 [ 2.  1. -2.]


`Experiment: How Fast is Numpy?`

In [12]:
import numpy as np
import time

size = 1_000_000
matrix_size = 1000

# Generate random data
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

array1 = np.arange(size)
array2 = np.arange(size)

# 1. Element-wise Addition
# Using Python Lists
start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
list_addition_time = time.time() - start_time
print(f"Python Lists Addition Time: {list_addition_time:.5f} seconds")

# Using NumPy Arrays
start_time = time.time()
numpy_addition = array1 + array2
numpy_addition_time = time.time() - start_time
print(f"NumPy Arrays Addition Time: {numpy_addition_time:.5f} seconds")

# 2. Element-wise Multiplication
# Using Python Lists
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
list_multiplication_time = time.time() - start_time
print(f"\nPython Lists Multiplication Time: {list_multiplication_time:.5f} seconds")

# Using NumPy Arrays
start_time = time.time()
numpy_multiplication = array1 * array2
numpy_multiplication_time = time.time() - start_time
print(f"NumPy Arrays Multiplication Time: {numpy_multiplication_time:.5f} seconds")

# 3. Dot Product
# Using Python Lists
start_time = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(size))
list_dot_product_time = time.time() - start_time
print(f"\nPython Lists Dot Product Time: {list_dot_product_time:.5f} seconds")

# Using NumPy Arrays
start_time = time.time()
numpy_dot_product = np.dot(array1, array2)
numpy_dot_product_time = time.time() - start_time
print(f"NumPy Arrays Dot Product Time: {numpy_dot_product_time:.5f} seconds")

# 4. Matrix Multiplication
# Generate random matrices
list_matrix1 = [[j for j in range(matrix_size)] for i in range(matrix_size)]
list_matrix2 = [[j for j in range(matrix_size)] for i in range(matrix_size)]

numpy_matrix1 = np.arange(matrix_size ** 2).reshape(matrix_size, matrix_size)
numpy_matrix2 = np.arange(matrix_size ** 2).reshape(matrix_size, matrix_size)

# Using Python Lists
start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]
list_matrix_multiplication_time = time.time() - start_time
print(f"\nPython Lists Matrix Multiplication Time: {list_matrix_multiplication_time:.5f} seconds")

# Using NumPy Arrays
start_time = time.time()
numpy_matrix_multiplication = np.dot(numpy_matrix1, numpy_matrix2)
numpy_matrix_multiplication_time = time.time() - start_time
print(f"NumPy Arrays Matrix Multiplication Time: {numpy_matrix_multiplication_time:.5f} seconds")


Python Lists Addition Time: 0.10923 seconds
NumPy Arrays Addition Time: 0.00814 seconds

Python Lists Multiplication Time: 0.12768 seconds
NumPy Arrays Multiplication Time: 0.00698 seconds

Python Lists Dot Product Time: 0.09790 seconds
NumPy Arrays Dot Product Time: 0.00201 seconds

Python Lists Matrix Multiplication Time: 175.06198 seconds
NumPy Arrays Matrix Multiplication Time: 1.78656 seconds
